//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ODataGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ODataGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, EQPARAM=7, DOLLAR=8, AMPERSAND=9, 
		COMMA=10, SQ=11, AND=12, OR=13, NOT=14, TRUE=15, FALSE=16, GT=17, GE=18, 
		LT=19, LE=20, EQ=21, NE=22, LPAREN=23, RPAREN=24, DECIMAL=25, INT=26, 
		IDENTIFIER=27, STRINGLITERAL=28, WS=29;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "EQPARAM", "DOLLAR", "AMPERSAND", 
		"COMMA", "SQ", "AND", "OR", "NOT", "TRUE", "FALSE", "GT", "GE", "LT", 
		"LE", "EQ", "NE", "LPAREN", "RPAREN", "DECIMAL", "INT", "IDENTIFIER", 
		"STRINGLITERAL", "WS"
	};


	public ODataGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ODataGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'filter'", "'select'", "'count'", "'orderby'", "'asc'", "'desc'", 
		"'='", "'$'", "'&'", "','", null, null, null, null, null, null, null, 
		null, null, null, null, null, "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, "EQPARAM", "DOLLAR", "AMPERSAND", 
		"COMMA", "SQ", "AND", "OR", "NOT", "TRUE", "FALSE", "GT", "GE", "LT", 
		"LE", "EQ", "NE", "LPAREN", "RPAREN", "DECIMAL", "INT", "IDENTIFIER", 
		"STRINGLITERAL", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ODataGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ODataGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1F', '\xE9', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', 's', 
		'\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x5', 
		'\xE', 'y', '\n', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x5', '\xF', '\x84', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x5', '\x10', '\x8E', '\n', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\x9A', 
		'\n', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x5', '\x12', '\xA0', '\n', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x5', '\x13', '\xA6', '\n', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x5', '\x14', '\xAC', '\n', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x5', 
		'\x15', '\xB2', '\n', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x5', '\x16', '\xB8', '\n', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\xBE', '\n', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x6', '\x1A', '\xC7', '\n', '\x1A', '\r', 
		'\x1A', '\xE', '\x1A', '\xC8', '\x3', '\x1B', '\x5', '\x1B', '\xCC', '\n', 
		'\x1B', '\x3', '\x1B', '\x6', '\x1B', '\xCF', '\n', '\x1B', '\r', '\x1B', 
		'\xE', '\x1B', '\xD0', '\x3', '\x1C', '\x3', '\x1C', '\a', '\x1C', '\xD5', 
		'\n', '\x1C', '\f', '\x1C', '\xE', '\x1C', '\xD8', '\v', '\x1C', '\x3', 
		'\x1D', '\x3', '\x1D', '\a', '\x1D', '\xDC', '\n', '\x1D', '\f', '\x1D', 
		'\xE', '\x1D', '\xDF', '\v', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1E', '\x6', '\x1E', '\xE4', '\n', '\x1E', '\r', '\x1E', '\xE', '\x1E', 
		'\xE5', '\x3', '\x1E', '\x3', '\x1E', '\x2', '\x2', '\x1F', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', 
		'/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', 
		'\x39', '\x1E', ';', '\x1F', '\x3', '\x2', '\a', '\x3', '\x2', ')', ')', 
		'\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x5', '\x2', '\v', '\f', '\xE', '\xF', '\"', '\"', '\x2', 
		'\xFB', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x3', '=', '\x3', '\x2', 
		'\x2', '\x2', '\x5', '\x44', '\x3', '\x2', '\x2', '\x2', '\a', 'K', '\x3', 
		'\x2', '\x2', '\x2', '\t', 'Q', '\x3', '\x2', '\x2', '\x2', '\v', 'Y', 
		'\x3', '\x2', '\x2', '\x2', '\r', ']', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '\x11', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x13', '\x66', '\x3', '\x2', '\x2', '\x2', '\x15', 'h', '\x3', 
		'\x2', '\x2', '\x2', '\x17', 'j', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'r', '\x3', '\x2', '\x2', '\x2', '\x1B', 'x', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', '\x83', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x8D', '\x3', '\x2', 
		'\x2', '\x2', '!', '\x99', '\x3', '\x2', '\x2', '\x2', '#', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '%', '\xA5', '\x3', '\x2', '\x2', '\x2', '\'', '\xAB', 
		'\x3', '\x2', '\x2', '\x2', ')', '\xB1', '\x3', '\x2', '\x2', '\x2', '+', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '-', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '/', '\xBF', '\x3', '\x2', '\x2', '\x2', '\x31', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\xC3', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\xCB', '\x3', '\x2', '\x2', '\x2', '\x37', '\xD2', '\x3', '\x2', '\x2', 
		'\x2', '\x39', '\xD9', '\x3', '\x2', '\x2', '\x2', ';', '\xE3', '\x3', 
		'\x2', '\x2', '\x2', '=', '>', '\a', 'h', '\x2', '\x2', '>', '?', '\a', 
		'k', '\x2', '\x2', '?', '@', '\a', 'n', '\x2', '\x2', '@', '\x41', '\a', 
		'v', '\x2', '\x2', '\x41', '\x42', '\a', 'g', '\x2', '\x2', '\x42', '\x43', 
		'\a', 't', '\x2', '\x2', '\x43', '\x4', '\x3', '\x2', '\x2', '\x2', '\x44', 
		'\x45', '\a', 'u', '\x2', '\x2', '\x45', '\x46', '\a', 'g', '\x2', '\x2', 
		'\x46', 'G', '\a', 'n', '\x2', '\x2', 'G', 'H', '\a', 'g', '\x2', '\x2', 
		'H', 'I', '\a', '\x65', '\x2', '\x2', 'I', 'J', '\a', 'v', '\x2', '\x2', 
		'J', '\x6', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', '\x65', '\x2', 
		'\x2', 'L', 'M', '\a', 'q', '\x2', '\x2', 'M', 'N', '\a', 'w', '\x2', 
		'\x2', 'N', 'O', '\a', 'p', '\x2', '\x2', 'O', 'P', '\a', 'v', '\x2', 
		'\x2', 'P', '\b', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\a', 'q', '\x2', 
		'\x2', 'R', 'S', '\a', 't', '\x2', '\x2', 'S', 'T', '\a', '\x66', '\x2', 
		'\x2', 'T', 'U', '\a', 'g', '\x2', '\x2', 'U', 'V', '\a', 't', '\x2', 
		'\x2', 'V', 'W', '\a', '\x64', '\x2', '\x2', 'W', 'X', '\a', '{', '\x2', 
		'\x2', 'X', '\n', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', '\x63', 
		'\x2', '\x2', 'Z', '[', '\a', 'u', '\x2', '\x2', '[', '\\', '\a', '\x65', 
		'\x2', '\x2', '\\', '\f', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', 
		'\x66', '\x2', '\x2', '^', '_', '\a', 'g', '\x2', '\x2', '_', '`', '\a', 
		'u', '\x2', '\x2', '`', '\x61', '\a', '\x65', '\x2', '\x2', '\x61', '\xE', 
		'\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\a', '?', '\x2', '\x2', '\x63', 
		'\x10', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', '&', '\x2', 
		'\x2', '\x65', '\x12', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\a', 
		'(', '\x2', '\x2', 'g', '\x14', '\x3', '\x2', '\x2', '\x2', 'h', 'i', 
		'\a', '.', '\x2', '\x2', 'i', '\x16', '\x3', '\x2', '\x2', '\x2', 'j', 
		'k', '\t', '\x2', '\x2', '\x2', 'k', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'l', 'm', '\a', '\x43', '\x2', '\x2', 'm', 'n', '\a', 'P', '\x2', '\x2', 
		'n', 's', '\a', '\x46', '\x2', '\x2', 'o', 'p', '\a', '\x63', '\x2', '\x2', 
		'p', 'q', '\a', 'p', '\x2', '\x2', 'q', 's', '\a', '\x66', '\x2', '\x2', 
		'r', 'l', '\x3', '\x2', '\x2', '\x2', 'r', 'o', '\x3', '\x2', '\x2', '\x2', 
		's', '\x1A', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', 'Q', '\x2', '\x2', 
		'u', 'y', '\a', 'T', '\x2', '\x2', 'v', 'w', '\a', 'q', '\x2', '\x2', 
		'w', 'y', '\a', 't', '\x2', '\x2', 'x', 't', '\x3', '\x2', '\x2', '\x2', 
		'x', 'v', '\x3', '\x2', '\x2', '\x2', 'y', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'z', '{', '\a', 'P', '\x2', '\x2', '{', '|', '\a', 'Q', '\x2', 
		'\x2', '|', '\x84', '\a', 'V', '\x2', '\x2', '}', '\x84', '\a', '#', '\x2', 
		'\x2', '~', '\x7F', '\a', '>', '\x2', '\x2', '\x7F', '\x84', '\a', '@', 
		'\x2', '\x2', '\x80', '\x81', '\a', 'p', '\x2', '\x2', '\x81', '\x82', 
		'\a', 'q', '\x2', '\x2', '\x82', '\x84', '\a', 'v', '\x2', '\x2', '\x83', 
		'z', '\x3', '\x2', '\x2', '\x2', '\x83', '}', '\x3', '\x2', '\x2', '\x2', 
		'\x83', '~', '\x3', '\x2', '\x2', '\x2', '\x83', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '\x84', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', 
		'\a', 'V', '\x2', '\x2', '\x86', '\x87', '\a', 'T', '\x2', '\x2', '\x87', 
		'\x88', '\a', 'W', '\x2', '\x2', '\x88', '\x8E', '\a', 'G', '\x2', '\x2', 
		'\x89', '\x8A', '\a', 'v', '\x2', '\x2', '\x8A', '\x8B', '\a', 't', '\x2', 
		'\x2', '\x8B', '\x8C', '\a', 'w', '\x2', '\x2', '\x8C', '\x8E', '\a', 
		'g', '\x2', '\x2', '\x8D', '\x85', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x89', '\x3', '\x2', '\x2', '\x2', '\x8E', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\a', 'H', '\x2', '\x2', '\x90', '\x91', '\a', 
		'\x43', '\x2', '\x2', '\x91', '\x92', '\a', 'N', '\x2', '\x2', '\x92', 
		'\x93', '\a', 'U', '\x2', '\x2', '\x93', '\x9A', '\a', 'G', '\x2', '\x2', 
		'\x94', '\x95', '\a', 'h', '\x2', '\x2', '\x95', '\x96', '\a', '\x63', 
		'\x2', '\x2', '\x96', '\x97', '\a', 'n', '\x2', '\x2', '\x97', '\x98', 
		'\a', 'u', '\x2', '\x2', '\x98', '\x9A', '\a', 'g', '\x2', '\x2', '\x99', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\x99', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\"', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\a', 
		'i', '\x2', '\x2', '\x9C', '\xA0', '\a', 'v', '\x2', '\x2', '\x9D', '\x9E', 
		'\a', 'I', '\x2', '\x2', '\x9E', '\xA0', '\a', 'V', '\x2', '\x2', '\x9F', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '$', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\a', 
		'i', '\x2', '\x2', '\xA2', '\xA6', '\a', 'g', '\x2', '\x2', '\xA3', '\xA4', 
		'\a', 'I', '\x2', '\x2', '\xA4', '\xA6', '\a', 'G', '\x2', '\x2', '\xA5', 
		'\xA1', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '&', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\a', 
		'n', '\x2', '\x2', '\xA8', '\xAC', '\a', 'v', '\x2', '\x2', '\xA9', '\xAA', 
		'\a', 'N', '\x2', '\x2', '\xAA', '\xAC', '\a', 'V', '\x2', '\x2', '\xAB', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '(', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\a', 
		'n', '\x2', '\x2', '\xAE', '\xB2', '\a', 'g', '\x2', '\x2', '\xAF', '\xB0', 
		'\a', 'N', '\x2', '\x2', '\xB0', '\xB2', '\a', 'G', '\x2', '\x2', '\xB1', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xAF', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '*', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', '\a', 
		'g', '\x2', '\x2', '\xB4', '\xB8', '\a', 's', '\x2', '\x2', '\xB5', '\xB6', 
		'\a', 'G', '\x2', '\x2', '\xB6', '\xB8', '\a', 'S', '\x2', '\x2', '\xB7', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB5', '\x3', '\x2', '\x2', 
		'\x2', '\xB8', ',', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBA', '\a', 
		'p', '\x2', '\x2', '\xBA', '\xBE', '\a', 'g', '\x2', '\x2', '\xBB', '\xBC', 
		'\a', 'P', '\x2', '\x2', '\xBC', '\xBE', '\a', 'G', '\x2', '\x2', '\xBD', 
		'\xB9', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBB', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '.', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\a', 
		'*', '\x2', '\x2', '\xC0', '\x30', '\x3', '\x2', '\x2', '\x2', '\xC1', 
		'\xC2', '\a', '+', '\x2', '\x2', '\xC2', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xC3', '\xC4', '\x5', '\x35', '\x1B', '\x2', '\xC4', '\xC6', '\a', 
		'\x30', '\x2', '\x2', '\xC5', '\xC7', '\t', '\x3', '\x2', '\x2', '\xC6', 
		'\xC5', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\xC8', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC9', '\x3', 
		'\x2', '\x2', '\x2', '\xC9', '\x34', '\x3', '\x2', '\x2', '\x2', '\xCA', 
		'\xCC', '\a', '/', '\x2', '\x2', '\xCB', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\xCB', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xCF', '\t', '\x3', '\x2', '\x2', '\xCE', 
		'\xCD', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '\xD0', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD1', '\x3', 
		'\x2', '\x2', '\x2', '\xD1', '\x36', '\x3', '\x2', '\x2', '\x2', '\xD2', 
		'\xD6', '\t', '\x4', '\x2', '\x2', '\xD3', '\xD5', '\t', '\x5', '\x2', 
		'\x2', '\xD4', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD8', '\x3', 
		'\x2', '\x2', '\x2', '\xD6', '\xD4', '\x3', '\x2', '\x2', '\x2', '\xD6', 
		'\xD7', '\x3', '\x2', '\x2', '\x2', '\xD7', '\x38', '\x3', '\x2', '\x2', 
		'\x2', '\xD8', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDD', '\x5', 
		'\x17', '\f', '\x2', '\xDA', '\xDC', '\t', '\x5', '\x2', '\x2', '\xDB', 
		'\xDA', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDF', '\x3', '\x2', '\x2', 
		'\x2', '\xDD', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\x3', 
		'\x2', '\x2', '\x2', '\xDE', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xDF', 
		'\xDD', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\x5', '\x17', '\f', 
		'\x2', '\xE1', ':', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xE4', '\t', 
		'\x6', '\x2', '\x2', '\xE3', '\xE2', '\x3', '\x2', '\x2', '\x2', '\xE4', 
		'\xE5', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE3', '\x3', '\x2', '\x2', 
		'\x2', '\xE5', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE7', '\x3', 
		'\x2', '\x2', '\x2', '\xE7', '\xE8', '\b', '\x1E', '\x2', '\x2', '\xE8', 
		'<', '\x3', '\x2', '\x2', '\x2', '\x14', '\x2', 'r', 'x', '\x83', '\x8D', 
		'\x99', '\x9F', '\xA5', '\xAB', '\xB1', '\xB7', '\xBD', '\xC8', '\xCB', 
		'\xD0', '\xD6', '\xDD', '\xE5', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
