//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ODataGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ODataGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, EQPARAM=3, DOLLAR=4, AMPERSAND=5, COMMA=6, SQ=7, AND=8, 
		OR=9, NOT=10, TRUE=11, FALSE=12, GT=13, GE=14, LT=15, LE=16, EQ=17, NE=18, 
		LPAREN=19, RPAREN=20, DECIMAL=21, INT=22, IDENTIFIER=23, STRINGLITERAL=24, 
		WS=25;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "EQPARAM", "DOLLAR", "AMPERSAND", "COMMA", "SQ", "AND", 
		"OR", "NOT", "TRUE", "FALSE", "GT", "GE", "LT", "LE", "EQ", "NE", "LPAREN", 
		"RPAREN", "DECIMAL", "INT", "IDENTIFIER", "STRINGLITERAL", "WS"
	};


	public ODataGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ODataGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'filter'", "'count'", "'='", "'$'", "'&'", "','", null, null, null, 
		null, null, null, null, null, null, null, null, null, "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "EQPARAM", "DOLLAR", "AMPERSAND", "COMMA", "SQ", "AND", 
		"OR", "NOT", "TRUE", "FALSE", "GT", "GE", "LT", "LE", "EQ", "NE", "LPAREN", 
		"RPAREN", "DECIMAL", "INT", "IDENTIFIER", "STRINGLITERAL", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ODataGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ODataGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1B', '\xC9', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', 'S', '\n', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', 'Y', '\n', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', '\x64', '\n', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x5', '\f', 'n', '\n', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', 'z', '\n', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', 
		'\x80', '\n', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x5', '\xF', '\x86', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x5', '\x10', '\x8C', '\n', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\x92', 
		'\n', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x5', '\x12', '\x98', '\n', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x5', '\x13', '\x9E', '\n', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x6', '\x16', '\xA7', '\n', '\x16', '\r', '\x16', '\xE', 
		'\x16', '\xA8', '\x3', '\x17', '\x5', '\x17', '\xAC', '\n', '\x17', '\x3', 
		'\x17', '\x6', '\x17', '\xAF', '\n', '\x17', '\r', '\x17', '\xE', '\x17', 
		'\xB0', '\x3', '\x18', '\x3', '\x18', '\a', '\x18', '\xB5', '\n', '\x18', 
		'\f', '\x18', '\xE', '\x18', '\xB8', '\v', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\a', '\x19', '\xBC', '\n', '\x19', '\f', '\x19', '\xE', '\x19', 
		'\xBF', '\v', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x6', 
		'\x1A', '\xC4', '\n', '\x1A', '\r', '\x1A', '\xE', '\x1A', '\xC5', '\x3', 
		'\x1A', '\x3', '\x1A', '\x2', '\x2', '\x1B', '\x3', '\x3', '\x5', '\x4', 
		'\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', 
		'\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', 
		'\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', 
		'\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', 
		'\x31', '\x1A', '\x33', '\x1B', '\x3', '\x2', '\a', '\x3', '\x2', ')', 
		')', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x5', '\x2', '\v', '\f', '\xE', '\xF', '\"', '\"', '\x2', 
		'\xDB', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '\x35', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'<', '\x3', '\x2', '\x2', '\x2', '\a', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\t', '\x44', '\x3', '\x2', '\x2', '\x2', '\v', '\x46', '\x3', '\x2', 
		'\x2', '\x2', '\r', 'H', '\x3', '\x2', '\x2', '\x2', '\xF', 'J', '\x3', 
		'\x2', '\x2', '\x2', '\x11', 'R', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'X', '\x3', '\x2', '\x2', '\x2', '\x15', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x17', 'm', '\x3', '\x2', '\x2', '\x2', '\x19', 'y', '\x3', '\x2', 
		'\x2', '\x2', '\x1B', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '\x1F', '\x8B', '\x3', '\x2', '\x2', '\x2', 
		'!', '\x91', '\x3', '\x2', '\x2', '\x2', '#', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '%', '\x9D', '\x3', '\x2', '\x2', '\x2', '\'', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', ')', '\xA1', '\x3', '\x2', '\x2', '\x2', '+', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '-', '\xAB', '\x3', '\x2', '\x2', '\x2', '/', '\xB2', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\xB9', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\xC3', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', 'h', 
		'\x2', '\x2', '\x36', '\x37', '\a', 'k', '\x2', '\x2', '\x37', '\x38', 
		'\a', 'n', '\x2', '\x2', '\x38', '\x39', '\a', 'v', '\x2', '\x2', '\x39', 
		':', '\a', 'g', '\x2', '\x2', ':', ';', '\a', 't', '\x2', '\x2', ';', 
		'\x4', '\x3', '\x2', '\x2', '\x2', '<', '=', '\a', '\x65', '\x2', '\x2', 
		'=', '>', '\a', 'q', '\x2', '\x2', '>', '?', '\a', 'w', '\x2', '\x2', 
		'?', '@', '\a', 'p', '\x2', '\x2', '@', '\x41', '\a', 'v', '\x2', '\x2', 
		'\x41', '\x6', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\a', '?', 
		'\x2', '\x2', '\x43', '\b', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', 
		'\a', '&', '\x2', '\x2', '\x45', '\n', '\x3', '\x2', '\x2', '\x2', '\x46', 
		'G', '\a', '(', '\x2', '\x2', 'G', '\f', '\x3', '\x2', '\x2', '\x2', 'H', 
		'I', '\a', '.', '\x2', '\x2', 'I', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'J', 'K', '\t', '\x2', '\x2', '\x2', 'K', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'M', '\a', '\x43', '\x2', '\x2', 'M', 'N', '\a', 'P', '\x2', 
		'\x2', 'N', 'S', '\a', '\x46', '\x2', '\x2', 'O', 'P', '\a', '\x63', '\x2', 
		'\x2', 'P', 'Q', '\a', 'p', '\x2', '\x2', 'Q', 'S', '\a', '\x66', '\x2', 
		'\x2', 'R', 'L', '\x3', '\x2', '\x2', '\x2', 'R', 'O', '\x3', '\x2', '\x2', 
		'\x2', 'S', '\x12', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\a', 'Q', '\x2', 
		'\x2', 'U', 'Y', '\a', 'T', '\x2', '\x2', 'V', 'W', '\a', 'q', '\x2', 
		'\x2', 'W', 'Y', '\a', 't', '\x2', '\x2', 'X', 'T', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'V', '\x3', '\x2', '\x2', '\x2', 'Y', '\x14', '\x3', '\x2', 
		'\x2', '\x2', 'Z', '[', '\a', 'P', '\x2', '\x2', '[', '\\', '\a', 'Q', 
		'\x2', '\x2', '\\', '\x64', '\a', 'V', '\x2', '\x2', ']', '\x64', '\a', 
		'#', '\x2', '\x2', '^', '_', '\a', '>', '\x2', '\x2', '_', '\x64', '\a', 
		'@', '\x2', '\x2', '`', '\x61', '\a', 'p', '\x2', '\x2', '\x61', '\x62', 
		'\a', 'q', '\x2', '\x2', '\x62', '\x64', '\a', 'v', '\x2', '\x2', '\x63', 
		'Z', '\x3', '\x2', '\x2', '\x2', '\x63', ']', '\x3', '\x2', '\x2', '\x2', 
		'\x63', '^', '\x3', '\x2', '\x2', '\x2', '\x63', '`', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\x16', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', 
		'V', '\x2', '\x2', '\x66', 'g', '\a', 'T', '\x2', '\x2', 'g', 'h', '\a', 
		'W', '\x2', '\x2', 'h', 'n', '\a', 'G', '\x2', '\x2', 'i', 'j', '\a', 
		'v', '\x2', '\x2', 'j', 'k', '\a', 't', '\x2', '\x2', 'k', 'l', '\a', 
		'w', '\x2', '\x2', 'l', 'n', '\a', 'g', '\x2', '\x2', 'm', '\x65', '\x3', 
		'\x2', '\x2', '\x2', 'm', 'i', '\x3', '\x2', '\x2', '\x2', 'n', '\x18', 
		'\x3', '\x2', '\x2', '\x2', 'o', 'p', '\a', 'H', '\x2', '\x2', 'p', 'q', 
		'\a', '\x43', '\x2', '\x2', 'q', 'r', '\a', 'N', '\x2', '\x2', 'r', 's', 
		'\a', 'U', '\x2', '\x2', 's', 'z', '\a', 'G', '\x2', '\x2', 't', 'u', 
		'\a', 'h', '\x2', '\x2', 'u', 'v', '\a', '\x63', '\x2', '\x2', 'v', 'w', 
		'\a', 'n', '\x2', '\x2', 'w', 'x', '\a', 'u', '\x2', '\x2', 'x', 'z', 
		'\a', 'g', '\x2', '\x2', 'y', 'o', '\x3', '\x2', '\x2', '\x2', 'y', 't', 
		'\x3', '\x2', '\x2', '\x2', 'z', '\x1A', '\x3', '\x2', '\x2', '\x2', '{', 
		'|', '\a', 'i', '\x2', '\x2', '|', '\x80', '\a', 'v', '\x2', '\x2', '}', 
		'~', '\a', 'I', '\x2', '\x2', '~', '\x80', '\a', 'V', '\x2', '\x2', '\x7F', 
		'{', '\x3', '\x2', '\x2', '\x2', '\x7F', '}', '\x3', '\x2', '\x2', '\x2', 
		'\x80', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\a', 'i', 
		'\x2', '\x2', '\x82', '\x86', '\a', 'g', '\x2', '\x2', '\x83', '\x84', 
		'\a', 'I', '\x2', '\x2', '\x84', '\x86', '\a', 'G', '\x2', '\x2', '\x85', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x86', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\a', 
		'n', '\x2', '\x2', '\x88', '\x8C', '\a', 'v', '\x2', '\x2', '\x89', '\x8A', 
		'\a', 'N', '\x2', '\x2', '\x8A', '\x8C', '\a', 'V', '\x2', '\x2', '\x8B', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', 
		'\x2', '\x8C', ' ', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'n', '\x2', '\x2', '\x8E', '\x92', '\a', 'g', '\x2', '\x2', '\x8F', '\x90', 
		'\a', 'N', '\x2', '\x2', '\x90', '\x92', '\a', 'G', '\x2', '\x2', '\x91', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x91', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\x92', '\"', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\a', 
		'g', '\x2', '\x2', '\x94', '\x98', '\a', 's', '\x2', '\x2', '\x95', '\x96', 
		'\a', 'G', '\x2', '\x2', '\x96', '\x98', '\a', 'S', '\x2', '\x2', '\x97', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '$', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', 
		'p', '\x2', '\x2', '\x9A', '\x9E', '\a', 'g', '\x2', '\x2', '\x9B', '\x9C', 
		'\a', 'P', '\x2', '\x2', '\x9C', '\x9E', '\a', 'G', '\x2', '\x2', '\x9D', 
		'\x99', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9B', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '&', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', 
		'*', '\x2', '\x2', '\xA0', '(', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', 
		'\a', '+', '\x2', '\x2', '\xA2', '*', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'\xA4', '\x5', '-', '\x17', '\x2', '\xA4', '\xA6', '\a', '\x30', '\x2', 
		'\x2', '\xA5', '\xA7', '\t', '\x3', '\x2', '\x2', '\xA6', '\xA5', '\x3', 
		'\x2', '\x2', '\x2', '\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', ',', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAC', '\a', 
		'/', '\x2', '\x2', '\xAB', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAE', '\x3', '\x2', '\x2', 
		'\x2', '\xAD', '\xAF', '\t', '\x3', '\x2', '\x2', '\xAE', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '.', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB6', '\t', 
		'\x4', '\x2', '\x2', '\xB3', '\xB5', '\t', '\x5', '\x2', '\x2', '\xB4', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB8', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xB7', '\x30', '\x3', '\x2', '\x2', '\x2', '\xB8', 
		'\xB6', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBD', '\x5', '\xF', '\b', 
		'\x2', '\xBA', '\xBC', '\t', '\x5', '\x2', '\x2', '\xBB', '\xBA', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xBB', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\xC0', '\xC1', '\x5', '\xF', '\b', '\x2', '\xC1', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC4', '\t', '\x6', '\x2', 
		'\x2', '\xC3', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC5', '\x3', 
		'\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'\xC6', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', '\xC7', '\xC8', '\b', '\x1A', '\x2', '\x2', '\xC8', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x14', '\x2', 'R', 'X', '\x63', 'm', 'y', '\x7F', 
		'\x85', '\x8B', '\x91', '\x97', '\x9D', '\xA8', '\xAB', '\xB0', '\xB6', 
		'\xBD', '\xC5', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
