name: Main
env:
  app_release: false
  app_conf: Release
  nuget_url: https://api.nuget.org/v3/index.json 
  
on:
  push:
    branches: 
        - master
    tags: 
        - '**'
  pull_request:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Configure
      run: |
        echo "app_version=`git describe --tags`" >> $GITHUB_ENV
        echo "app_release=`(git describe --tags --exact-match>/dev/null 2>&1 && echo true) || echo false`" >> $GITHUB_ENV
    - name: Status
      run: echo "Release=$app_release, version=$app_version" 
    - name: Build
      run: dotnet build -c $app_conf -p:Version=$app_version -p:InformationalVersion="$app_version:$GITHUB_SHA"
    - name: Test
      run: dotnet test -c $app_conf --no-build
    - name: Pack
      working-directory: nuget
      run: dotnet pack -c $app_conf --no-build -o ./artifacts -p:Version=$app_version -p:CommitSHA=$GITHUB_SHA
    - uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./artifacts
    - name: Publish
      if: env.app_release == 'true'
      env:
        NUGETKEY: ${{ secrets.NUGET_KEY }}
      working-directory: ./artifacts
      run: dotnet nuget push *.nupkg -s $nuget_url -k $NUGETKEY   


